# Generated by Django 5.2.4 on 2025-08-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_referencia', models.CharField(help_text="Um nome interno para identificar este prompt. Ex: 'Post Instagram - Padrão V2'", max_length=100, unique=True)),
                ('template_do_prompt', models.TextField(help_text='O texto do prompt. Use chaves como {{caracteristicas}} para inserir os dados do imóvel.')),
                ('em_uso', models.BooleanField(default=False, help_text='Marque esta opção para que este seja o prompt ativo usado por todo o sistema.')),
                ('notas', models.TextField(blank=True, help_text='Notas internas para o superusuário sobre este prompt.', null=True)),
            ],
            options={
                'verbose_name': 'Modelo de Prompt da IA',
                'verbose_name_plural': 'Modelos de Prompt da IA',
            },
        ),
        migrations.CreateModel(
            name='OpcaoVozDaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O nome da voz, que será exibido para a imobiliária.', max_length=50, unique=True)),
                ('descricao', models.CharField(help_text='Uma breve descrição para explicar o estilo desta voz.', max_length=255)),
                ('instrucao_ia', models.TextField(help_text="Instrução específica para a IA sobre como aplicar esta voz. Ex: 'Use adjetivos sofisticados e foque em exclusividade.'")),
            ],
            options={
                'verbose_name': 'Opção de Voz da Marca',
                'verbose_name_plural': 'Opções de Voz da Marca',
                'ordering': ['nome'],
            },
        ),
    ]
