# Generated by Django 5.0.1 on 2026-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_modelo', models.CharField(max_length=100, unique=True, verbose_name='Nome de Identificação')),
                ('template_do_prompt', models.TextField(help_text='O texto do prompt. Use {{user_query}} para busca ou {{imovel_data}} para descrição.')),
                ('em_uso_busca', models.BooleanField(default=False, help_text='Marca este prompt como o principal para as buscas no site público.', verbose_name='Em uso para Busca por IA')),
                ('em_uso_descricao', models.BooleanField(default=False, help_text='Marca este prompt como o principal para gerar descrições no painel.', verbose_name='Em uso para Gerar Descrição de Imóvel')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Prompt de IA',
                'verbose_name_plural': 'Modelos de Prompt de IA',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoVozDaMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O nome da voz, que será exibido para a imobiliária.', max_length=50, unique=True)),
                ('descricao', models.CharField(help_text='Uma breve descrição para explicar o estilo desta voz.', max_length=255)),
                ('instrucao_ia', models.TextField(help_text="Instrução específica para a IA sobre como aplicar esta voz. Ex: 'Use adjetivos sofisticados e foque em exclusividade.'")),
            ],
            options={
                'verbose_name': 'Opção de Voz da Marca',
                'verbose_name_plural': 'Opções de Voz da Marca',
                'ordering': ['nome'],
            },
        ),
    ]
