# Generated by Django 5.2.4 on 2025-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelodeprompt',
            name='em_uso_busca',
            field=models.BooleanField(default=False, help_text='Marque esta opção para que este seja o prompt ativo para a busca com IA.'),
        ),
    ]
