# Generated by Django 5.0.1 on 2026-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelodeprompt',
            name='modelo_api',
            field=models.CharField(choices=[('gemini-1.5-flash', 'Gemini 1.5 Flash (Rápido/Econômico)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Raciocínio Avançado)'), ('gemini-1.0-pro', 'Gemini 1.0 Pro (Legado)')], default='gemini-1.5-flash', help_text="Escolha 'Flash' para velocidade ou 'Pro' para melhor raciocínio.", max_length=50, verbose_name='Modelo de IA'),
        ),
    ]
