# Generated by Django 5.0.3 on 2025-10-29 22:30 (Final Re-written for definitive fix)
import uuid
import datetime
import django.db.models.manager
from django.db import migrations, models
import django.utils.timezone


# --- FUNÇÃO DE MIGRAÇÃO PARA GARANTIR NOMES ÚNICOS ---
def popular_nomes_unicos(apps, schema_editor):
    """
    Atribui um nome único a cada linha existente na tabela ModeloDePrompt
    para evitar a UniqueViolation, usando um QuerySet seguro (values_list).
    """
    ModeloDePrompt = apps.get_model('app_config_ia', 'ModeloDePrompt')
    
    # Buscamos apenas os PKs, garantindo que o QuerySet não tenta ordenar por campos que ainda não existem.
    pks = ModeloDePrompt.objects.values_list('pk', flat=True)
    
    for i, pk in enumerate(pks):
        # Para evitar erros de salvamento em migrações, usamos o update direto.
        unique_name = f"Prompt-Antigo-{pk}-{uuid.uuid4().hex[:6]}"
        ModeloDePrompt.objects.filter(pk=pk).update(nome_do_modelo=unique_name)
# --- FIM DA FUNÇÃO ---


class Migration(migrations.Migration):

    dependencies = [
        ('app_config_ia', '0002_modelodeprompt_em_uso_busca'),
    ]

    operations = [
        # --- 1. Adiciona Campos de Data Primeiro (Para evitar FieldError) ---
        # Removido os RemoveField de data_atualizacao/data_criacao que não existiam na 0002
        migrations.AddField(
            model_name='modelodeprompt',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Última Atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelodeprompt',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),

        # --- 2. Remove Campos Antigos (Que falham menos após campos de data existirem) ---
        migrations.RemoveField(
            model_name='modelodeprompt',
            name='em_uso',
        ),
        migrations.RemoveField(
            model_name='modelodeprompt',
            name='nome_referencia',
        ),
        migrations.RemoveField(
            model_name='modelodeprompt',
            name='notas',
        ),
        
        # --- 3. Adição do Campo nome_do_modelo e Unicidade (3 Passos) ---

        # 3.1. Adiciona o campo nome_do_modelo permitindo NULO e SEM UNICIDADE (temporariamente)
        migrations.AddField(
            model_name='modelodeprompt',
            name='nome_do_modelo',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome de Identificação'),
        ),

        # 3.2. Executa a função Python para preencher os valores únicos em todas as linhas
        migrations.RunPython(popular_nomes_unicos, migrations.RunPython.noop),

        # 3.3. Altera o campo nome_do_modelo para NÃO NULO e Adiciona a unicidade
        migrations.AlterField(
            model_name='modelodeprompt',
            name='nome_do_modelo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome de Identificação'),
        ),
        
        # --- 4. Adiciona Novos Campos e Altera Atributos ---

        migrations.AlterModelOptions(
            name='modelodeprompt',
            options={'ordering': ['-data_atualizacao'], 'verbose_name': 'Modelo de Prompt de IA', 'verbose_name_plural': 'Modelos de Prompt de IA'},
        ),
        migrations.AddField(
            model_name='modelodeprompt',
            name='em_uso_descricao',
            field=models.BooleanField(default=False, help_text='Marca este prompt como o principal para gerar descrições no painel.', verbose_name='Em uso para Gerar Descrição de Imóvel'),
        ),
        migrations.AlterField(
            model_name='modelodeprompt',
            name='em_uso_busca',
            field=models.BooleanField(default=False, help_text='Marca este prompt como o principal para as buscas no site público.', verbose_name='Em uso para Busca por IA'),
        ),
        migrations.AlterField(
            model_name='modelodeprompt',
            name='template_do_prompt',
            field=models.TextField(help_text='O texto do prompt. Use {{user_query}} para busca ou {{imovel_data}} para descrição.'),
        ),
    ]