# Generated by Django 5.0.1 on 2026-01-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config_ia', '0002_modelodeprompt_modelo_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodeprompt',
            name='modelo_api',
            field=models.CharField(choices=[('gemini-1.5-flash', 'Rápido (Gemini 1.5 Flash)'), ('gemini-1.5-pro', 'Pro (Gemini 1.5 Pro)'), ('gemini-2.0-flash-thinking-exp-01-21', 'Raciocínio (Gemini 2.0 Flash Thinking)')], default='gemini-1.5-flash', help_text='Selecione a inteligência por trás deste prompt.', max_length=50, verbose_name='Modelo de IA'),
        ),
    ]
