# Generated by Django 5.2.4 on 2025-10-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config_ia', '0003_alter_modelodeprompt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodeprompt',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modelodeprompt',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
