# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INOPERANTE', 'Inoperante/Quebrado')], default='BOM', max_length=20)),
                ('descricao_avaria', models.TextField(blank=True, help_text='Descreva detalhes ou avarias', null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_vistorias.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Vistoria de Entrada'), ('SAIDA', 'Vistoria de Saída'), ('PERIODICA', 'Vistoria Periódica')], max_length=20)),
                ('data_vistoria', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('leitura_agua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Água')),
                ('leitura_luz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Luz')),
                ('leitura_gas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Gás')),
                ('chaves_devolvidas', models.TextField(blank=True, null=True, verbose_name='Chaves Devolvidas')),
                ('realizado_por_nome', models.CharField(blank=True, help_text='Nome do vistoriador responsável', max_length=150, null=True)),
                ('exige_assinatura_proprietario', models.BooleanField(default=False, verbose_name='Exigir assinatura do proprietário')),
                ('assinatura_locatario', models.ImageField(blank=True, null=True, upload_to='assinaturas/locatarios/%Y/%m/')),
                ('assinatura_responsavel', models.ImageField(blank=True, null=True, upload_to='assinaturas/responsaveis/%Y/%m/')),
                ('assinatura_proprietario', models.ImageField(blank=True, null=True, upload_to='assinaturas/proprietarios/%Y/%m/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='app_contratos.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='ambiente',
            name='vistoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='app_vistorias.vistoria'),
        ),
        migrations.CreateModel(
            name='VistoriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='vistorias/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_vistorias.itemvistoria')),
            ],
        ),
    ]
