# Generated by Django 5.2.4 on 2025-12-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contratos', '0014_contrato_excluido_alter_contrato_status_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Ambiente (ex: Cozinha)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='Item (ex: Pintura, Porta)')),
                ('estado', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular (com marcas de uso)'), ('RUIM', 'Ruim / Danificado'), ('NA', 'Não Aplicável')], default='BOM', max_length=20, verbose_name='Estado')),
                ('descricao_avaria', models.TextField(blank=True, null=True, verbose_name='Descrição de Avaria/Detalhes')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_vistorias.ambientevistoria')),
            ],
        ),
        migrations.CreateModel(
            name='FotoVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='vistorias/fotos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_vistorias.itemvistoria')),
            ],
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Vistoria de Entrada'), ('SAIDA', 'Vistoria de Saída'), ('PERIODICA', 'Vistoria Periódica')], max_length=20, verbose_name='Tipo de Vistoria')),
                ('data_vistoria', models.DateField(verbose_name='Data da Realização')),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('arquivo_laudo_assinado', models.FileField(blank=True, null=True, upload_to='vistorias/laudos/', verbose_name='Laudo Assinado (PDF)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='app_contratos.contrato', verbose_name='Contrato')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-data_vistoria'],
            },
        ),
        migrations.AddField(
            model_name='ambientevistoria',
            name='vistoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='app_vistorias.vistoria'),
        ),
    ]
