# Generated by Django 5.2.4 on 2025-12-16 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0014_contrato_excluido_alter_contrato_status_contrato'),
        ('app_vistorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambientevistoria',
            name='vistoria',
        ),
        migrations.AlterModelOptions(
            name='vistoria',
            options={},
        ),
        migrations.RenameField(
            model_name='vistoria',
            old_name='data_cadastro',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vistoria',
            old_name='data_atualizacao',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='arquivo_laudo_assinado',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='observacoes_gerais',
        ),
        migrations.AddField(
            model_name='vistoria',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemvistoria',
            name='descricao_avaria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemvistoria',
            name='estado',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INOPERANTE', 'Inoperante')], default='BOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemvistoria',
            name='item',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='app_contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='data_vistoria',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Vistoria de Entrada'), ('SAIDA', 'Vistoria de Saída'), ('PERIODICA', 'Vistoria Periódica')], max_length=20),
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='app_vistorias.vistoria')),
            ],
        ),
        migrations.AlterField(
            model_name='itemvistoria',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_vistorias.ambiente'),
        ),
        migrations.CreateModel(
            name='VistoriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='vistorias/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_vistorias.itemvistoria')),
            ],
        ),
        migrations.DeleteModel(
            name='FotoVistoria',
        ),
        migrations.DeleteModel(
            name='AmbienteVistoria',
        ),
    ]
