# Generated by Django 5.2.4 on 2025-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vistorias', '0002_remove_ambientevistoria_vistoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistoria',
            old_name='created_at',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='vistoriafoto',
            old_name='uploaded_at',
            new_name='data_upload',
        ),
        migrations.RenameField(
            model_name='vistoriafoto',
            old_name='foto',
            new_name='imagem',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vistoria',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='realizado_por_nome',
            field=models.CharField(blank=True, help_text='Nome do vistoriador responsável', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itemvistoria',
            name='descricao_avaria',
            field=models.TextField(blank=True, help_text='Descreva detalhes ou avarias', null=True),
        ),
        migrations.AlterField(
            model_name='itemvistoria',
            name='estado',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INOPERANTE', 'Inoperante/Quebrado')], default='BOM', max_length=20),
        ),
    ]
