# Generated by Django 5.2.4 on 2025-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vistorias', '0003_rename_created_at_vistoria_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='assinatura_locatario',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/%Y/%m/'),
        ),
    ]
