# Generated by Django 5.2.4 on 2025-12-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vistorias', '0004_vistoria_assinatura_locatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='assinatura_responsavel',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/responsaveis/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='assinatura_locatario',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/locatarios/%Y/%m/'),
        ),
    ]
