# Generated by Django 5.2.4 on 2025-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vistorias', '0005_vistoria_assinatura_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='assinatura_proprietario',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/proprietarios/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='exige_assinatura_proprietario',
            field=models.BooleanField(default=False, verbose_name='Exigir assinatura do proprietário'),
        ),
    ]
