# Generated by Django 5.2.4 on 2025-12-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vistorias', '0006_vistoria_assinatura_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria',
            name='chaves_devolvidas',
            field=models.TextField(blank=True, null=True, verbose_name='Chaves Devolvidas'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='leitura_agua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Água'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='leitura_gas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Gás'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='leitura_luz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Leitura Luz'),
        ),
    ]
