services:
  db:
    image: postgres:13.2-alpine
    container_name: imobcloud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=imobcloud_db
      - POSTGRES_USER=imobuser
      - POSTGRES_PASSWORD=imobpassword
      - POSTGRES_HOST_AUTH_METHOD=md5
    restart: unless-stopped

  cache:
    image: redis:6.2-alpine
    container_name: imobcloud_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    container_name: imobcloud_backend
    build:
      context: ./backend  # <-- CORRIGIDO
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app   # <-- CORRIGIDO
    env_file:
      - ./backend/.env   # <-- CORRIGIDO
    depends_on:
      - db
      - cache
    restart: unless-stopped

  frontend:
    container_name: imobcloud_frontend
    build:
      context: ./frontend # <-- CORRIGIDO
    volumes:
      - ./frontend:/app  # <-- CORRIGIDO
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: