# Generated by Django 5.2.4 on 2025-08-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Imobiliária')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('subdominio', models.CharField(max_length=100, unique=True, verbose_name='Subdomínio')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('ativa', models.BooleanField(default=True, verbose_name='Imobiliária Ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Imobiliária',
                'verbose_name_plural': 'Imobiliárias',
            },
        ),
    ]
