# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_config_ia', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Mensal Básico, Anual Pro', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Plano')),
                ('dias_ciclo', models.IntegerField(default=30, help_text='A cada quantos dias vence? (30 = Mensal, 365 = Anual)')),
                ('dias_para_bloqueio', models.IntegerField(default=5, help_text='Quantos dias após o vencimento o sistema deve bloquear o acesso? (Ex: 5 dias de tolerância)')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('subdominio', models.CharField(max_length=255, unique=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para Notificações')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('creci', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('facebook_user_access_token', models.CharField(blank=True, max_length=512, null=True, verbose_name='Token de Acesso do Usuário FB')),
                ('facebook_page_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Página do Facebook')),
                ('facebook_page_access_token', models.CharField(blank=True, max_length=512, null=True, verbose_name='Token de Acesso da Página do Facebook')),
                ('instagram_business_account_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Conta Business do Instagram')),
                ('google_gemini_api_key', models.CharField(blank=True, help_text='Chave de acesso para o serviço Gemini/Google AI.', max_length=255, null=True, verbose_name='Chave API Google Gemini')),
                ('cor_primaria', models.CharField(default='#007bff', help_text='Cor principal para o site público (código hexadecimal).', max_length=7, verbose_name='Cor Principal do Site')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_vencimento_atual', models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento')),
                ('status_financeiro', models.CharField(choices=[('ATIVO', 'Ativo (Em dia)'), ('PENDENTE', 'Pagamento Pendente (Em tolerância)'), ('BLOQUEADO', 'Acesso Bloqueado (Inadimplente)'), ('CANCELADO', 'Cancelado'), ('GRATIS', 'Período de Teste')], default='GRATIS', max_length=20, verbose_name='Status da Assinatura')),
                ('voz_da_marca_preferida', models.ForeignKey(blank=True, help_text='A voz da marca que a IA usará para as publicações desta imobiliária.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_config_ia.opcaovozdamarca')),
                ('plano_contratado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plano', verbose_name='Plano Atual')),
            ],
            options={
                'verbose_name_plural': 'Imobiliárias',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É Administrador')),
                ('is_corretor', models.BooleanField(default=True, verbose_name='É Corretor')),
                ('creci', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco_logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('endereco_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('endereco_estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('endereco_cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('google_json_file', models.FileField(blank=True, null=True, upload_to='google_credentials/', verbose_name='Arquivo de Credenciais do Google')),
                ('google_calendar_token', models.TextField(blank=True, null=True, verbose_name='Token de Acesso do Google Calendar')),
                ('assinatura', models.ImageField(blank=True, help_text='Imagem da assinatura para uso automático em documentos.', null=True, upload_to='assinaturas_usuarios/', verbose_name='Assinatura Digital')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('imobiliaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_imobiliaria', to='core.imobiliaria')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Notificação', max_length=100)),
                ('mensagem', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='INFO', max_length=50)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
