# Generated by Django 5.2.4 on 2025-08-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imobiliaria',
            options={'verbose_name_plural': 'Imobiliárias'},
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='telefone_contato',
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='subdominio',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imobiliaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_imobiliaria', to='core.imobiliaria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
