# Generated by Django 5.0.1 on 2026-01-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(default='https://imobhome.com.br', max_length=255, verbose_name='URL do Sistema')),
                ('base_public_url', models.CharField(default='https://imobhome.com.br', max_length=255, verbose_name='URL Pública Base')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Host SMTP')),
                ('email_port', models.IntegerField(default=587, verbose_name='Porta SMTP')),
                ('email_host_user', models.CharField(max_length=255, verbose_name='Usuário SMTP (Email)')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='Senha SMTP (App Password)')),
                ('default_from_email', models.CharField(default='ImobHome <noreply@imobhome.com.br>', max_length=255, verbose_name='Remetente Padrão')),
                ('google_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google API Key (Maps/Gemini Global)')),
                ('cloudinary_cloud_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cloudinary Cloud Name')),
                ('cloudinary_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cloudinary API Key')),
                ('cloudinary_api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cloudinary API Secret')),
                ('modo_manutencao', models.BooleanField(default=False, verbose_name='Modo Manutenção')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
