# Generated by Django 5.2.4 on 2025-08-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imobiliaria_options_remove_imobiliaria_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para Notificações'),
        ),
    ]
