# Generated by Django 5.0.1 on 2026-01-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaoglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imobiliarias_logos/', verbose_name='Logo da Imobiliária'),
        ),
    ]
