# Generated by Django 5.0.1 on 2026-01-19 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imobiliaria_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imobiliaria',
            options={'ordering': ['nome_fantasia', 'nome'], 'verbose_name': 'Imobiliária', 'verbose_name_plural': 'Imobiliárias'},
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE Principal'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='cnae_secundarios',
            field=models.TextField(blank=True, null=True, verbose_name='CNAEs Secundários'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ / CPF'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='creci_documento',
            field=models.FileField(blank=True, null=True, upload_to='imobiliarias/creci/', verbose_name='Documento CRECI (Upload)'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='creci_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CRECI'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='creci_situacao',
            field=models.CharField(blank=True, default='Ativo', max_length=50, null=True, verbose_name='Situação do CRECI'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='creci_tipo',
            field=models.CharField(choices=[('JURIDICO', 'Jurídico'), ('FISICO', 'Físico')], default='JURIDICO', max_length=20, verbose_name='Tipo de CRECI'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='creci_uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF do CRECI'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='creci_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do CRECI'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='data_fundacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fundação'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='email_financeiro',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Financeiro'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='email_suporte',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Suporte'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza Jurídica'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='outros_links',
            field=models.TextField(blank=True, null=True, verbose_name='Outros Links Sociais'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='outros_registros',
            field=models.TextField(blank=True, null=True, verbose_name='Outros Registros Profissionais'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='regiao_administrativa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Região Administrativa'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='imobiliarias/assinaturas/', verbose_name='Assinatura Digital'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_documento',
            field=models.FileField(blank=True, null=True, upload_to='imobiliarias/documentos/', verbose_name='Documento de Identificação'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Responsável'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_orgao_emissor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG do Responsável'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Responsável'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='responsavel_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp do Responsável'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('SUSPENSA', 'Suspensa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=20, verbose_name='Status da Empresa'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Celular'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], default='PJ', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='ID Interno (UUID)'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ (Legado)'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='creci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI (Legado)'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Principal (Notificações)'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome (Sistema)'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='subdominio',
            field=models.CharField(max_length=255, unique=True, verbose_name='Subdomínio'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (Legado/Celular)'),
        ),
    ]
