# Generated by Django 5.2.4 on 2025-08-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imobiliaria_email_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CORRETOR', 'Corretor')], default='CORRETOR', max_length=10, verbose_name='Cargo'),
        ),
    ]
