# Generated by Django 5.2.4 on 2025-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='creci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco_estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco_logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
