# Generated by Django 5.0.1 on 2026-01-19 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imobiliaria_options_imobiliaria_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imobiliaria',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Interno (UUID)'),
        ),
    ]
