# Generated by Django 5.0.1 on 2026-01-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_imobiliaria_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo (Legado)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios_fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imobiliarias_logos/', verbose_name='Logo da Imobiliária (Principal)'),
        ),
    ]
