# Generated by Django 5.2.4 on 2025-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_creci_perfilusuario_endereco_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='google_json_file',
            field=models.FileField(blank=True, null=True, upload_to='google_credentials/', verbose_name='Arquivo de Credenciais do Google'),
        ),
    ]
