# Generated by Django 5.2.4 on 2025-08-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilusuario_google_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='google_calendar_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token de Acesso do Google Calendar'),
        ),
    ]
