# Generated by Django 5.0.1 on 2026-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_imobiliaria_logo_perfilusuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha SMTP (App Password)'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário SMTP (Email)'),
        ),
    ]
