# Generated by Django 5.0.1 on 2026-01-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_configuracaoglobal_email_host_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='facebook_app_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Aplicativo do Facebook'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='facebook_app_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Segredo do Aplicativo do Facebook'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='voz_da_marca_preferida',
            field=models.TextField(blank=True, help_text='A voz da marca que a IA usará para as publicações desta imobiliária (Ex: Formal, Casual, Luxuoso).', null=True),
        ),
    ]
