# Generated by Django 5.2.4 on 2025-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='facebook_page_access_token',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Token de Acesso da Página do Facebook'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Página do Facebook'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Conta Business do Instagram'),
        ),
    ]
