# Generated by Django 5.2.4 on 2025-08-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_imobiliaria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imobiliaria',
            options={'verbose_name': 'Imobiliária', 'verbose_name_plural': 'Imobiliárias'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='endereco_bairro',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='endereco_cep',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='endereco_cidade',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='endereco_estado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='endereco_logradouro',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='endereco_numero',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='imobiliaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_de_usuario', to='core.imobiliaria'),
        ),
    ]
