# Generated by Django 5.2.4 on 2025-08-13 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config_ia', '0001_initial'),
        ('core', '0009_imobiliaria_facebook_page_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='voz_da_marca_preferida',
            field=models.ForeignKey(blank=True, help_text='A voz da marca que a IA usará para as publicações desta imobiliária.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_config_ia.opcaovozdamarca'),
        ),
    ]
