# Generated by Django 5.2.4 on 2025-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_imobiliaria_voz_da_marca_preferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='cor_primaria',
            field=models.CharField(default='#007bff', help_text='Cor principal para o site público (código hexadecimal).', max_length=7, verbose_name='Cor Principal do Site'),
        ),
    ]
