# Generated by Django 5.2.4 on 2025-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_imobiliaria_cor_primaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='creci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI'),
        ),
    ]
