# Generated by Django 5.2.4 on 2025-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_imobiliaria_cnpj_imobiliaria_creci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='É Administrador'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_corretor',
            field=models.BooleanField(default=True, verbose_name='É Corretor'),
        ),
    ]
