# Generated by Django 5.2.4 on 2025-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_perfilusuario_cargo_perfilusuario_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='assinatura',
            field=models.ImageField(blank=True, help_text='Imagem da assinatura para uso automático em documentos.', null=True, upload_to='assinaturas_usuarios/', verbose_name='Assinatura Digital'),
        ),
    ]
