# Generated by Django 5.2.4 on 2025-12-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_perfilusuario_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(default='INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(default='Notificação', max_length=100),
        ),
    ]
