# Generated by Django 5.2.4 on 2025-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notificacao_tipo_notificacao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='google_gemini_api_key',
            field=models.CharField(blank=True, help_text='Chave de acesso para o serviço Gemini/Google AI.', max_length=255, null=True, verbose_name='Chave API Google Gemini'),
        ),
    ]
