# Generated by Django 5.0.4 on 2025-12-16 12:45
# ATENÇÃO:
# Se o Django gerar outro número (ex: 0018),
# renomeie este arquivo para manter a sequência correta.

import datetime
from django.db import migrations, models
from django.utils import timezone
import django.contrib.auth.models
import django.db.models.deletion
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.apps.registry import Apps


# -------------------------------------------------
# FUNÇÃO: GARANTE USERNAME ÚNICO ANTES DO UNIQUE
# -------------------------------------------------
def set_unique_usernames(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    PerfilUsuario = apps.get_model('core', 'PerfilUsuario')

    for perfil in PerfilUsuario.objects.all():
        if not perfil.username:
            perfil.username = f'usuario_antigo_{perfil.id}'

        # NÃO usar métodos de modelo em migração
        if perfil.password in ('', ' '):
            perfil.password = '!'

        if perfil.is_superuser is None:
            perfil.is_superuser = False

        if perfil.is_staff is None:
            perfil.is_staff = False

        if perfil.is_active is None:
            perfil.is_active = True

        perfil.save()



class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0016_imobiliaria_google_gemini_api_key'),
    ]

    operations = [

        # -------------------------------------------------
        # MANAGER
        # -------------------------------------------------
        migrations.AlterModelManagers(
            name='perfilusuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),

        # -------------------------------------------------
        # REMOVE RELAÇÃO ANTIGA COM AUTH.USER
        # -------------------------------------------------
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),

        # -------------------------------------------------
        # CAMPOS DO ABSTRACTUSER (SEM UNIQUE AINDA)
        # -------------------------------------------------
        migrations.AddField(
            model_name='perfilusuario',
            name='date_joined',
            field=models.DateTimeField(default=timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                related_name='user_set',
                related_query_name='user',
                to='auth.group',
                verbose_name='groups',
            ),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='password',
            field=models.CharField(default=' ', max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='user_permissions',
            field=models.ManyToManyField(
                blank=True,
                related_name='user_set',
                related_query_name='user',
                to='auth.permission',
                verbose_name='user permissions',
            ),
        ),

        # -------------------------------------------------
        # USERNAME SEM UNIQUE (PASSO CRÍTICO)
        # -------------------------------------------------
        migrations.AddField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(
                max_length=150,
                null=True,
                blank=True,
                verbose_name='username',
            ),
        ),

        # -------------------------------------------------
        # CORRIGE OS DADOS EXISTENTES
        # -------------------------------------------------
        migrations.RunPython(set_unique_usernames, migrations.RunPython.noop),

        # -------------------------------------------------
        # APLICA UNIQUE APÓS DADOS CORRIGIDOS
        # -------------------------------------------------
        migrations.AlterField(
            model_name='perfilusuario',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                verbose_name='username',
            ),
        ),

        # -------------------------------------------------
        # IMOBILIÁRIA
        # -------------------------------------------------
        migrations.AddField(
            model_name='imobiliaria',
            name='data_cadastro',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 1, 1, 0, 0, tzinfo=datetime.UTC),
                verbose_name='Data de Cadastro',
            ),
            preserve_default=False,
        ),

        # -------------------------------------------------
        # META E FK
        # -------------------------------------------------
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='imobiliaria',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='usuarios_imobiliaria',
                to='core.imobiliaria',
            ),
        ),
    ]
