# Generated by Django 5.2.4 on 2025-12-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_perfilusuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='facebook_user_access_token',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Token de Acesso do Usuário FB'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato'),
        ),
    ]
