# Generated by Django 5.2.4 on 2026-01-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_imobiliaria_facebook_user_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Mensal Básico, Anual Pro', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Plano')),
                ('dias_ciclo', models.IntegerField(default=30, help_text='A cada quantos dias vence? (30 = Mensal, 365 = Anual)')),
                ('dias_para_bloqueio', models.IntegerField(default=5, help_text='Quantos dias após o vencimento o sistema deve bloquear o acesso? (Ex: 5 dias de tolerância)')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='data_vencimento_atual',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='status_financeiro',
            field=models.CharField(choices=[('ATIVO', 'Ativo (Em dia)'), ('PENDENTE', 'Pagamento Pendente (Em tolerância)'), ('BLOQUEADO', 'Acesso Bloqueado (Inadimplente)'), ('CANCELADO', 'Cancelado'), ('GRATIS', 'Período de Teste')], default='GRATIS', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='plano_contratado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plano', verbose_name='Plano Atual'),
        ),
    ]
