# Generated by Django 5.2.4 on 2025-08-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Imóvel')),
                ('finalidade', models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel'), ('Ambos', 'Ambos')], max_length=50, verbose_name='Finalidade')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor de Venda')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor de Aluguel')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Total (m²)')),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Construída (m²)')),
                ('quartos', models.IntegerField(default=0, verbose_name='Quartos')),
                ('suites', models.IntegerField(default=0, verbose_name='Suítes')),
                ('banheiros', models.IntegerField(default=0, verbose_name='Banheiros')),
                ('vagas_garagem', models.IntegerField(default=0, verbose_name='Vagas de Garagem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Alugado', 'Alugado'), ('Vendido', 'Vendido'), ('Em Negociação', 'Em Negociação')], default='Disponível', max_length=50, verbose_name='Status')),
                ('aceita_financiamento', models.BooleanField(default=False, verbose_name='Aceita Financiamento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis_imagens/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Imagem')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app_imoveis.imovel', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens dos Imóveis',
                'ordering': ['principal', 'data_upload'],
            },
        ),
    ]
