# Generated by Django 5.2.4 on 2025-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel'), ('Ambos', 'Venda e Aluguel')], max_length=50, verbose_name='Finalidade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Alugado', 'Alugado'), ('Vendido', 'Vendido'), ('Em Negociação', 'Em Negociação'), ('Desativado', 'Desativado')], default='Disponível', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Terreno', 'Terreno'), ('Sala Comercial', 'Sala Comercial'), ('Galpão', 'Galpão'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Imóvel'),
        ),
    ]
