# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0002_initial'),
        ('app_imoveis', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_propriedade', to='app_clientes.cliente', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='imagemimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app_imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='contatoimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='app_imoveis.imovel', verbose_name='Imóvel'),
        ),
    ]
