# Generated by Django 5.2.4 on 2025-08-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0002_alter_imovel_finalidade_alter_imovel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Interessado')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (Opcional)')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_contato', models.DateTimeField(auto_now_add=True, verbose_name='Data do Contato')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='app_imoveis.imovel', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Contato de Imóvel',
                'verbose_name_plural': 'Contatos de Imóveis',
                'ordering': ['-data_contato'],
            },
        ),
    ]
