# Generated by Django 5.0.1 on 2026-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='conteudo_html_autorizacao',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo HTML da Autorização'),
        ),
    ]
