# Generated by Django 5.2.4 on 2025-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0003_contatoimovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoimovel',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
