# Generated by Django 5.2.4 on 2025-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0004_contatoimovel_arquivado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='aceita_financiamento',
            new_name='financiavel',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='descricao',
        ),
        migrations.AddField(
            model_name='imovel',
            name='academia',
            field=models.BooleanField(default=False, verbose_name='Academia'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='aceita_permuta',
            field=models.BooleanField(default=False, verbose_name='Aceita Permuta (Troca)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='aceita_pet',
            field=models.BooleanField(default=False, verbose_name='Aceita Pet'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='andar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Andar (se apartamento)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='ano_construcao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Construção'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='aquecimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Aquecimento'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='ar_condicionado',
            field=models.BooleanField(default=False, verbose_name='Ar Condicionado'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_servico',
            field=models.BooleanField(default=False, verbose_name='Área de Serviço'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área do Terreno (m²)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Útil (m²)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='bicicletario',
            field=models.BooleanField(default=False, verbose_name='Bicicletário'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='churrasqueira_condominio',
            field=models.BooleanField(default=False, verbose_name='Churrasqueira no Condomínio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='churrasqueira_privativa',
            field=models.BooleanField(default=False, verbose_name='Churrasqueira Privativa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='closet',
            field=models.BooleanField(default=False, verbose_name='Closet'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='codigo_referencia',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Código de Referência'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='copa',
            field=models.BooleanField(default=False, verbose_name='Copa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cozinha',
            field=models.BooleanField(default=False, verbose_name='Cozinha'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='descricao_completa',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada / Observações'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='despensa',
            field=models.BooleanField(default=False, verbose_name='Despensa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='dimensao_direita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lado Direito (m)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='dimensao_esquerda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lado Esquerdo (m)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='dimensao_frente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frente (m)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='dimensao_fundos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fundos (m)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='disponibilidade',
            field=models.CharField(blank=True, choices=[('IMEDIATA', 'Imediata'), ('OCUPADO', 'Ocupado'), ('DESOCUPADO', 'Desocupado')], max_length=20, null=True, verbose_name='Disponibilidade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='documentacao_ok',
            field=models.BooleanField(default=False, verbose_name='Documentação OK'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='elevador',
            field=models.BooleanField(default=False, verbose_name='Elevador'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='escritorio',
            field=models.BooleanField(default=False, verbose_name='Escritório'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='espaco_gourmet',
            field=models.BooleanField(default=False, verbose_name='Espaço Gourmet'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='espaco_pet',
            field=models.BooleanField(default=False, verbose_name='Espaço Pet'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='gas_central',
            field=models.BooleanField(default=False, verbose_name='Gás Central'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='hidrometro_individual',
            field=models.BooleanField(default=False, verbose_name='Hidrômetro Individual'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='lavabo',
            field=models.BooleanField(default=False, verbose_name='Lavabo'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='localizacao_condominio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização no Condomínio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='mobiliado',
            field=models.BooleanField(default=False, verbose_name='Mobiliado / Semimobiliado'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='moveis_planejados',
            field=models.BooleanField(default=False, verbose_name='Móveis Planejados'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_pavimentos',
            field=models.IntegerField(default=1, verbose_name='Número de Pavimentos'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='pe_direito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pé-Direito (m)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='piscina_condominio',
            field=models.BooleanField(default=False, verbose_name='Piscina no Condomínio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='piscina_privativa',
            field=models.BooleanField(default=False, verbose_name='Piscina Privativa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='piso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Piso'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='playground',
            field=models.BooleanField(default=False, verbose_name='Playground'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='portao_eletronico',
            field=models.BooleanField(default=False, verbose_name='Portão Eletrônico'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='portaria_24h',
            field=models.BooleanField(default=False, verbose_name='Portaria 24h'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='posicao_solar',
            field=models.CharField(blank=True, choices=[('NORTE', 'Norte (Sol da Manhã)'), ('SUL', 'Sul'), ('LESTE', 'Leste (Sol da Manhã)'), ('OESTE', 'Oeste (Sol da Tarde)')], max_length=10, null=True, verbose_name='Posição Solar'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quadra_esportiva',
            field=models.BooleanField(default=False, verbose_name='Quadra Poliesportiva'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quitado',
            field=models.BooleanField(default=False, verbose_name='Imóvel Quitado'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sala_estar',
            field=models.BooleanField(default=False, verbose_name='Sala de Estar'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sala_jantar',
            field=models.BooleanField(default=False, verbose_name='Sala de Jantar'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sala_tv',
            field=models.BooleanField(default=False, verbose_name='Sala de TV'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='salao_festas',
            field=models.BooleanField(default=False, verbose_name='Salão de Festas'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sauna',
            field=models.BooleanField(default=False, verbose_name='Sauna'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='situacao',
            field=models.CharField(blank=True, choices=[('NOVO', 'Novo'), ('USADO', 'Usado'), ('NA_PLANTA', 'Na Planta')], max_length=20, null=True, verbose_name='Situação do Imóvel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_construcao',
            field=models.CharField(blank=True, choices=[('ALVENARIA', 'Alvenaria'), ('PRE_MOLDADO', 'Pré-Moldado'), ('MISTA', 'Mista'), ('MADEIRA', 'Madeira')], max_length=20, null=True, verbose_name='Tipo de Construção'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='titulo_anuncio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Anúncio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='unidades_por_andar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unidades por Andar'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vaga_coberta',
            field=models.BooleanField(default=False, verbose_name='Vaga Coberta'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vaga_privativa',
            field=models.BooleanField(default=False, verbose_name='Vaga Privativa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vagas_visitantes',
            field=models.BooleanField(default=False, verbose_name='Vagas para Visitantes'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_condominio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Condomínio'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_iptu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do IPTU (Anual)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='varanda',
            field=models.BooleanField(default=False, verbose_name='Varanda / Sacada'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vista',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vista (Ex: Mar, Montanha)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço Completo (Rua, Número)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial'), ('RURAL', 'Rural')], max_length=50, verbose_name='Finalidade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('A_VENDA', 'À Venda'), ('PARA_ALUGAR', 'Para Alugar'), ('VENDIDO', 'Vendido'), ('ALUGADO', 'Alugado'), ('EM_CONSTRUCAO', 'Em Construção'), ('DESATIVADO', 'Desativado')], default='A_VENDA', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('TERRENO', 'Terreno'), ('SALA_COMERCIAL', 'Sala Comercial'), ('GALPAO', 'Galpão'), ('RURAL', 'Rural'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Imóvel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas_garagem',
            field=models.IntegerField(default=0, verbose_name='Número de Vagas'),
        ),
    ]
