# Generated by Django 5.2.4 on 2025-08-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0005_tarefa'),
        ('app_imoveis', '0005_rename_aceita_financiamento_imovel_financiavel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemimovel',
            options={'ordering': ['-principal', '-data_upload'], 'verbose_name': 'Imagem do Imóvel', 'verbose_name_plural': 'Imagens dos Imóveis'},
        ),
        migrations.AddField(
            model_name='imovel',
            name='comissao_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão Acordada (%)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_captacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Captação / Início da Autorização'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_fim_exclusividade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim da Exclusividade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='documento_autorizacao',
            field=models.FileField(blank=True, null=True, upload_to='autorizacoes/', verbose_name='Documento de Autorização Assinado'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_matricula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Matrícula do Imóvel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='possui_exclusividade',
            field=models.BooleanField(default=False, verbose_name='Possui Contrato de Exclusividade?'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_propriedade', to='app_clientes.cliente', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='publicado_no_site',
            field=models.BooleanField(default=True, verbose_name='Publicar no site?'),
        ),
    ]
