# Generated by Django 5.2.4 on 2025-08-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0006_alter_imagemimovel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='data_fim_exclusividade',
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_fim_autorizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim da Autorização'),
        ),
    ]
