# Generated by Django 5.2.4 on 2025-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0007_remove_imovel_data_fim_exclusividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='informacoes_adicionais_autorizacao',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais para o Contrato'),
        ),
    ]
