# Generated by Django 5.2.4 on 2025-08-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0008_imovel_informacoes_adicionais_autorizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemimovel',
            options={'ordering': ['ordem']},
        ),
        migrations.RemoveField(
            model_name='imagemimovel',
            name='descricao',
        ),
        migrations.AddField(
            model_name='imagemimovel',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagemimovel',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagemimovel',
            name='imagem',
            field=models.ImageField(upload_to='imoveis_imagens/'),
        ),
        migrations.AlterField(
            model_name='imagemimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app_imoveis.imovel'),
        ),
        migrations.AlterField(
            model_name='imagemimovel',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
