# Generated by Django 5.2.4 on 2025-08-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0009_alter_imagemimovel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='posicao_chave',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Posição da Chave'),
        ),
    ]
