# Generated by Django 5.2.4 on 2025-08-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0010_imovel_posicao_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='configuracao_publica',
            field=models.JSONField(blank=True, default=dict, help_text='Configuração de visibilidade de campos específicos para o site público.'),
        ),
    ]
