# Generated by Django 5.2.4 on 2025-08-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0011_imovel_configuracao_publica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='logradouro',
            field=models.CharField(default='', max_length=255, verbose_name='Rua/Avenida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='outras_caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Outras Características'),
        ),
    ]
