# Generated by Django 5.2.4 on 2025-08-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(default=0, verbose_name="Quartos"),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(default=1, verbose_name="Banheiros"),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Área (m²)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Está Ativo?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "Imóveis",
                "ordering": ["-created_at"],
            },
        ),
    ]
