# Generated by Django 5.0.1 on 2026-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoRemessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='remessas/')),
            ],
            options={
                'verbose_name': 'Arquivo de Remessa',
                'verbose_name_plural': 'Arquivos de Remessa',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='retornos/')),
                ('log_processamento', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Arquivo de Retorno',
                'verbose_name_plural': 'Arquivos de Retorno',
                'ordering': ['-data_processamento'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosso_numero', models.CharField(max_length=20, verbose_name='Nosso Número')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Remessa'), ('ENVIADO', 'Enviado ao Banco'), ('PAGO', 'Pago'), ('BAIXADO', 'Baixado/Cancelado')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(choices=[('Bradesco', 'Bradesco'), ('Itau', 'Itaú'), ('Santander', 'Santander')], max_length=50, verbose_name='Banco')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret')),
                ('agencia', models.CharField(default='0000', help_text='Agência sem o dígito verificador.', max_length=10)),
                ('conta', models.CharField(default='00000', help_text='Número da conta sem o dígito verificador.', max_length=20)),
                ('convenio', models.CharField(default='0000000', help_text='Número do convênio ou cedente.', max_length=20)),
                ('certificado_file', models.FileField(blank=True, null=True, upload_to='bradesco_certs/', verbose_name='Arquivo do Certificado (CRT/PEM)')),
                ('chave_privada_file', models.FileField(blank=True, null=True, upload_to='bradesco_certs/', verbose_name='Arquivo da Chave Privada (KEY)')),
            ],
            options={
                'verbose_name': 'Configuração do Banco',
                'verbose_name_plural': 'Configurações dos Bancos',
            },
        ),
    ]
