# Generated by Django 5.2.4 on 2025-08-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_imobiliaria_voz_da_marca_preferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(choices=[('Bradesco', 'Bradesco'), ('Itau', 'Itaú'), ('Santander', 'Santander')], max_length=50, verbose_name='Banco')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
            ],
            options={
                'verbose_name': 'Configuração do Banco',
                'verbose_name_plural': 'Configurações dos Bancos',
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=255, verbose_name='Código de Barras')),
                ('linha_digitavel', models.CharField(max_length=255, verbose_name='Linha Digitável')),
                ('url_boleto', models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL do Boleto (PDF)')),
                ('status', models.CharField(choices=[('EMITIDO', 'Emitido'), ('REGISTRADO', 'Registrado'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='EMITIDO', max_length=50, verbose_name='Status do Boleto')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
