# Generated by Django 5.2.4 on 2025-08-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_boletos', '0001_initial'),
        ('app_financeiro', '0001_initial'),
        ('core', '0010_imobiliaria_voz_da_marca_preferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='transacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='app_financeiro.transacao', verbose_name='Transação Relacionada'),
        ),
        migrations.AddField(
            model_name='configuracaobanco',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='configuracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_boletos.configuracaobanco', verbose_name='Configuração de Banco'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaobanco',
            unique_together={('imobiliaria', 'nome_banco')},
        ),
    ]
