# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_boletos', '0001_initial'),
        ('app_financeiro', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoremessa',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='arquivoretorno',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='remessa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='app_boletos.arquivoremessa'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='app_boletos.arquivoretorno'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='transacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='app_financeiro.transacao'),
        ),
        migrations.AddField(
            model_name='configuracaobanco',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária'),
        ),
        migrations.AddField(
            model_name='arquivoretorno',
            name='configuracao_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_boletos.configuracaobanco'),
        ),
        migrations.AddField(
            model_name='arquivoremessa',
            name='configuracao_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_boletos.configuracaobanco'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaobanco',
            unique_together={('imobiliaria', 'nome_banco')},
        ),
    ]
