# Generated by Django 5.2.4 on 2025-08-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boletos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaobanco',
            name='certificado_file',
            field=models.FileField(blank=True, null=True, upload_to='bradesco_certs/', verbose_name='Arquivo do Certificado (CRT/PEM)'),
        ),
        migrations.AddField(
            model_name='configuracaobanco',
            name='chave_privada_file',
            field=models.FileField(blank=True, null=True, upload_to='bradesco_certs/', verbose_name='Arquivo da Chave Privada (KEY)'),
        ),
    ]
