# Generated by Django 5.2.4 on 2025-08-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boletos', '0003_configuracaobanco_certificado_file_and_more'),
        ('app_financeiro', '0002_popular_boleto_forma_pagamento'),
        ('core', '0010_imobiliaria_voz_da_marca_preferida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleto',
            options={},
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='configuracao',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='imobiliaria',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='linha_digitavel',
        ),
        migrations.RemoveField(
            model_name='boleto',
            name='url_boleto',
        ),
        migrations.AddField(
            model_name='boleto',
            name='nosso_numero',
            field=models.CharField(default='', max_length=20, verbose_name='Nosso Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleto',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracaobanco',
            name='agencia',
            field=models.CharField(default='0000', help_text='Agência sem o dígito verificador.', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracaobanco',
            name='conta',
            field=models.CharField(default='00000', help_text='Número da conta sem o dígito verificador.', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaobanco',
            name='convenio',
            field=models.CharField(default='0000000', help_text='Número do convênio ou cedente.', max_length=20),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Remessa'), ('ENVIADO', 'Enviado ao Banco'), ('PAGO', 'Pago'), ('BAIXADO', 'Baixado/Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='transacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='app_financeiro.transacao'),
        ),
        migrations.CreateModel(
            name='ArquivoRemessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='remessas/')),
                ('configuracao_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_boletos.configuracaobanco')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria')),
            ],
            options={
                'verbose_name': 'Arquivo de Remessa',
                'verbose_name_plural': 'Arquivos de Remessa',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.AddField(
            model_name='boleto',
            name='remessa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='app_boletos.arquivoremessa'),
        ),
        migrations.CreateModel(
            name='ArquivoRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='retornos/')),
                ('log_processamento', models.TextField(blank=True, null=True)),
                ('configuracao_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_boletos.configuracaobanco')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria')),
            ],
            options={
                'verbose_name': 'Arquivo de Retorno',
                'verbose_name_plural': 'Arquivos de Retorno',
                'ordering': ['-data_processamento'],
            },
        ),
        migrations.AddField(
            model_name='boleto',
            name='retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='app_boletos.arquivoretorno'),
        ),
    ]
