# Generated by Django 5.2.4 on 2025-08-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boletos', '0004_alter_boleto_options_remove_boleto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaobanco',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='configuracaobanco',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret'),
        ),
    ]
