# Generated by Django 5.0.1 on 2026-01-07 19:41

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIGACAO', 'Ligação'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('NOTA', 'Nota'), ('MUDANCA_FASE', 'Mudança de Fase')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='FISICA', max_length=8, verbose_name='Tipo de Pessoa')),
                ('documento', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo / Nome Fantasia')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='clientes_fotos/', verbose_name='Foto de Perfil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro (Rua, Av.)')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('preferencias_imovel', models.TextField(blank=True, null=True, verbose_name='Preferências de Imóvel')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('perfil_cliente', models.JSONField(blank=True, default=list, help_text='Lista de perfis/funções do cliente.', verbose_name='Perfis do Cliente (Interessado, Proprietário, etc.)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='FunilEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ordem', models.IntegerField(default=0)),
                ('probabilidade_fechamento', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['imobiliaria', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOportunidade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fase', models.CharField(choices=[('LEAD', 'Novo Lead'), ('CONTATO', 'Primeiro Contato'), ('VISITA', 'Visita Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Em Negociação'), ('GANHO', 'Negócio Ganho'), ('PERDIDO', 'Negócio Perdido')], default='LEAD', max_length=20)),
                ('fonte', models.CharField(blank=True, choices=[('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('ANUNCIO', 'Anúncio Online'), ('CLIENTE_ANTIGO', 'Cliente Antigo'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Fonte do Lead')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Oportunidade')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado')),
                ('probabilidade', models.IntegerField(default=10, verbose_name='Probabilidade de Fechamento')),
                ('motivo_perda', models.TextField(blank=True, null=True, verbose_name='Motivo da Perda')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Última Atualização')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Oportunidade de Venda',
                'verbose_name_plural': 'historical Oportunidades de Venda',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('LEAD', 'Novo Lead'), ('CONTATO', 'Primeiro Contato'), ('VISITA', 'Visita Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Em Negociação'), ('GANHO', 'Negócio Ganho'), ('PERDIDO', 'Negócio Perdido')], default='LEAD', max_length=20)),
                ('fonte', models.CharField(blank=True, choices=[('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('ANUNCIO', 'Anúncio Online'), ('CLIENTE_ANTIGO', 'Cliente Antigo'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Fonte do Lead')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Oportunidade')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado')),
                ('probabilidade', models.IntegerField(default=10, verbose_name='Probabilidade de Fechamento')),
                ('motivo_perda', models.TextField(blank=True, null=True, verbose_name='Motivo da Perda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
            ],
            options={
                'verbose_name': 'Oportunidade de Venda',
                'verbose_name_plural': 'Oportunidades de Venda',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_vencimento', models.DateTimeField()),
                ('concluida', models.BooleanField(default=False)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes_finalizacao', models.TextField(blank=True, null=True, verbose_name='Observações da Finalização')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('realizada', models.BooleanField(default=False, verbose_name='Visita Realizada')),
                ('localizacao_assinatura', models.CharField(blank=True, help_text='Lat/Long ou endereço GPS no momento da assinatura', max_length=255, null=True)),
                ('assinatura_cliente', models.ImageField(blank=True, null=True, upload_to='assinaturas_visitas/', verbose_name='Assinatura do Cliente')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura Cliente')),
                ('assinatura_corretor', models.ImageField(blank=True, null=True, upload_to='assinaturas_visitas/', verbose_name='Assinatura do Corretor')),
                ('data_assinatura_corretor', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura Corretor')),
            ],
        ),
    ]
