# Generated by Django 5.2.4 on 2025-08-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Tarefa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-data_conclusao'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora da Visita')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=50, verbose_name='Status da Visita')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('preferencias_imovel', models.TextField(blank=True, null=True, verbose_name='Preferências de Imóvel')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTA', 'Nota'), ('TAREFA', 'Tarefa'), ('VISITA', 'Visita Agendada'), ('CONTRATO', 'Contrato Criado'), ('EMAIL', 'Email'), ('LIGACAO', 'Ligação')], max_length=20, verbose_name='Tipo de Atividade')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão (para tarefas)')),
                ('concluida', models.BooleanField(default=False, verbose_name='Tarefa Concluída')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app_clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Atividade do Cliente',
                'verbose_name_plural': 'Atividades dos Clientes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria')),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Oportunidade')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Estimado do Negócio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Fechamento')),
                ('fonte', models.CharField(blank=True, choices=[('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('ANUNCIO', 'Anúncio Online'), ('CLIENTE_ANTIGO', 'Cliente Antigo'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Fonte do Lead')),
                ('motivo_perda', models.TextField(blank=True, null=True, verbose_name='Motivo da Perda')),
                ('data_proximo_contato', models.DateField(blank=True, null=True, verbose_name='Data do Próximo Contato')),
                ('probabilidade', models.PositiveIntegerField(default=10, verbose_name='Probabilidade de Fechamento (%)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='app_clientes.cliente', verbose_name='Cliente')),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_clientes.etapafunil', verbose_name='Fase do Funil')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
