# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0001_initial'),
        ('app_imoveis', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app_clientes.cliente'),
        ),
        migrations.AddField(
            model_name='funiletapa',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_funil', to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='historicaloportunidade',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_clientes.cliente'),
        ),
        migrations.AddField(
            model_name='historicaloportunidade',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaloportunidade',
            name='imobiliaria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='historicaloportunidade',
            name='imovel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='historicaloportunidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='app_clientes.cliente'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app_imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app_clientes.oportunidade'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente'),
        ),
        migrations.AddField(
            model_name='visita',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Corretor Responsável'),
        ),
        migrations.AddField(
            model_name='visita',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='visita',
            name='imoveis',
            field=models.ManyToManyField(related_name='visitas', to='app_imoveis.imovel', verbose_name='Imóveis Visitados'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('imobiliaria', 'documento')},
        ),
        migrations.AlterUniqueTogether(
            name='funiletapa',
            unique_together={('imobiliaria', 'titulo')},
        ),
    ]
