# Generated by Django 5.2.4 on 2025-08-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0001_initial'),
        ('app_imoveis', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app_imoveis.imovel', verbose_name='Imóvel de Interesse'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL, verbose_name='Corretor Responsável'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app_clientes.oportunidade', verbose_name='Oportunidade'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='visita',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária'),
        ),
        migrations.AddField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_imoveis.imovel', verbose_name='Imóvel'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('imobiliaria', 'cpf_cnpj')},
        ),
        migrations.AlterUniqueTogether(
            name='etapafunil',
            unique_together={('imobiliaria', 'nome')},
        ),
    ]
