# Generated by Django 5.0.1 on 2026-01-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0002_initial'),
        ('core', '0002_configuracaoglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='imobiliaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
