# Generated by Django 5.2.4 on 2025-08-05 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0002_cliente_ativo'),
        ('app_imoveis', '0004_contatoimovel_arquivado'),
        ('core', '0004_perfilusuario_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTA', 'Nota'), ('TAREFA', 'Tarefa'), ('VISITA', 'Visita Agendada'), ('CONTRATO', 'Contrato Criado'), ('EMAIL', 'Email'), ('LIGACAO', 'Ligação')], max_length=20, verbose_name='Tipo de Atividade')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão (para tarefas)')),
                ('concluida', models.BooleanField(default=False, verbose_name='Tarefa Concluída')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app_clientes.cliente', verbose_name='Cliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Atividade do Cliente',
                'verbose_name_plural': 'Atividades dos Clientes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Oportunidade')),
                ('fase', models.CharField(choices=[('LEAD', 'Novo Lead'), ('CONTATO', 'Primeiro Contato'), ('VISITA', 'Visita Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Em Negociação'), ('GANHO', 'Negócio Ganho'), ('PERDIDO', 'Negócio Perdido')], default='LEAD', max_length=20, verbose_name='Fase do Funil')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Estimado do Negócio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Fechamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='app_clientes.cliente', verbose_name='Cliente')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app_imoveis.imovel', verbose_name='Imóvel de Interesse')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL, verbose_name='Corretor Responsável')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
