# Generated by Django 5.0.1 on 2026-01-14 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0003_tarefa_imobiliaria_tarefa_prioridade_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
    ]
