# Generated by Django 5.2.4 on 2025-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0003_atividade_oportunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='data_proximo_contato',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Próximo Contato'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='fonte',
            field=models.CharField(blank=True, choices=[('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('ANUNCIO', 'Anúncio Online'), ('CLIENTE_ANTIGO', 'Cliente Antigo'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Fonte do Lead'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='motivo_perda',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Perda'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='probabilidade',
            field=models.PositiveIntegerField(default=10, verbose_name='Probabilidade de Fechamento (%)'),
        ),
    ]
