# Generated by Django 5.2.4 on 2025-08-06 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0004_oportunidade_data_proximo_contato_oportunidade_fonte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Tarefa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app_clientes.oportunidade', verbose_name='Oportunidade')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data_conclusao'],
            },
        ),
    ]
