# Generated by Django 5.0.1 on 2026-01-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0004_tarefa_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloportunidade',
            name='fase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_clientes.funiletapa', verbose_name='Fase do Funil'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='app_clientes.funiletapa', verbose_name='Fase do Funil'),
        ),
    ]
