# Generated by Django 5.2.4 on 2025-08-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0005_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app_clientes.oportunidade', verbose_name='Oportunidade'),
        ),
    ]
