# Generated by Django 5.0.1 on 2026-01-18 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0005_alter_historicaloportunidade_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloportunidade',
            name='data_fechamento_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Fechamento'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data_fechamento_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Fechamento'),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
