# Generated by Django 5.2.4 on 2025-08-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0006_alter_tarefa_oportunidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='data_proximo_contato',
        ),
    ]
