# Generated by Django 5.2.4 on 2025-08-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0007_remove_oportunidade_data_proximo_contato'),
        ('core', '0008_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseFunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_funil', to='core.imobiliaria')),
            ],
            options={
                'verbose_name': 'Fase do Funil',
                'verbose_name_plural': 'Fases do Funil',
                'ordering': ['ordem'],
                'unique_together': {('imobiliaria', 'nome')},
            },
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app_clientes.fasefunil', verbose_name='Fase do Funil'),
        ),
    ]
