# Generated by Django 5.2.4 on 2025-08-24 11:18

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0008_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
        ('app_imoveis', '0012_remove_imovel_endereco_imovel_complemento_and_more'),
        ('core', '0011_imobiliaria_cor_primaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oportunidade',
            options={'verbose_name': 'Oportunidade de Venda', 'verbose_name_plural': 'Oportunidades de Venda'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={},
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='concluida',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='data_fechamento',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='fonte',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='status',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_vencimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='data_visita',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('LIGACAO', 'Ligação'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('NOTA', 'Nota'), ('MUDANCA_FASE', 'Mudança de Fase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='app_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='fase',
            field=models.CharField(choices=[('LEAD', 'Novo Lead'), ('CONTATO', 'Primeiro Contato'), ('VISITA', 'Visita Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Em Negociação'), ('GANHO', 'Negócio Ganho'), ('PERDIDO', 'Negócio Perdido')], default='LEAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app_imoveis.imovel'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='probabilidade',
            field=models.IntegerField(default=10, verbose_name='Probabilidade de Fechamento'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='oportunidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app_clientes.oportunidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_imoveis.imovel'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalOportunidade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fase', models.CharField(choices=[('LEAD', 'Novo Lead'), ('CONTATO', 'Primeiro Contato'), ('VISITA', 'Visita Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Em Negociação'), ('GANHO', 'Negócio Ganho'), ('PERDIDO', 'Negócio Perdido')], default='LEAD', max_length=20)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Oportunidade')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado')),
                ('probabilidade', models.IntegerField(default=10, verbose_name='Probabilidade de Fechamento')),
                ('motivo_perda', models.TextField(blank=True, null=True, verbose_name='Motivo da Perda')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Última Atualização')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_clientes.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imobiliaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.imobiliaria')),
                ('imovel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_imoveis.imovel')),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Oportunidade de Venda',
                'verbose_name_plural': 'historical Oportunidades de Venda',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FunilEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ordem', models.IntegerField(default=0)),
                ('probabilidade_fechamento', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_funil', to='core.imobiliaria')),
            ],
            options={
                'verbose_name': 'Etapa do Funil',
                'verbose_name_plural': 'Etapas do Funil',
                'ordering': ['imobiliaria', 'ordem'],
                'unique_together': {('imobiliaria', 'titulo')},
            },
        ),
    ]
