# Generated by Django 5.2.4 on 2025-08-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0008_fasefunil_alter_oportunidade_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='fase',
            field=models.CharField(choices=[('LEAD', 'Novo Lead'), ('CONTATO', 'Primeiro Contato'), ('VISITA', 'Visita Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Em Negociação'), ('GANHO', 'Negócio Ganho'), ('PERDIDO', 'Negócio Perdido')], default='LEAD', max_length=20, verbose_name='Fase do Funil'),
        ),
        migrations.DeleteModel(
            name='FaseFunil',
        ),
    ]
