# Generated by Django 5.2.4 on 2025-08-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0008_alter_etapafunil_options_alter_tarefa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapafunil',
            options={'verbose_name': 'Etapa do Funil', 'verbose_name_plural': 'Etapas do Funil'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-data_conclusao'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='etapa_funil',
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_clientes.etapafunil', verbose_name='Fase do Funil'),
        ),
    ]
