# Generated by Django 5.2.4 on 2025-08-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0009_alter_etapafunil_options_alter_tarefa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapafunil',
            options={'ordering': ['ordem'], 'verbose_name': 'Etapa do Funil', 'verbose_name_plural': 'Etapas do Funil'},
        ),
        migrations.AddField(
            model_name='etapafunil',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
