# Generated by Django 5.2.4 on 2025-08-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0010_historicaloportunidade_informacoes_adicionais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloportunidade',
            name='informacoes_adicionais',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='informacoes_adicionais',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='oportunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='app_clientes.oportunidade'),
        ),
    ]
