# Generated by Django 5.2.4 on 2025-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0011_remove_historicaloportunidade_informacoes_adicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloportunidade',
            name='fonte',
            field=models.CharField(blank=True, choices=[('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('ANUNCIO', 'Anúncio Online'), ('CLIENTE_ANTIGO', 'Cliente Antigo'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Fonte do Lead'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='fonte',
            field=models.CharField(blank=True, choices=[('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('ANUNCIO', 'Anúncio Online'), ('CLIENTE_ANTIGO', 'Cliente Antigo'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Fonte do Lead'),
        ),
    ]
