# Generated by Django 5.2.4 on 2025-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0012_historicaloportunidade_fonte_oportunidade_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='observacoes_finalizacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Finalização'),
        ),
    ]
