# Generated by Django 5.2.4 on 2025-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0013_tarefa_observacoes_finalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloportunidade',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
    ]
