# Generated by Django 5.2.4 on 2025-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0014_historicaloportunidade_informacoes_adicionais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes_fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro (Rua, Av.)'),
        ),
    ]
