# Generated by Django 5.2.4 on 2025-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0015_remove_cliente_endereco_cliente_complemento_and_more'),
        ('core', '0011_imobiliaria_cor_primaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf_cnpj',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='funiletapa',
            name='probabilidade_fechamento',
            field=models.IntegerField(default=0, help_text='Porcentagem'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('imobiliaria', 'documento')},
        ),
    ]
