# Generated by Django 5.2.4 on 2025-09-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0016_rename_cpf_cnpj_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='FISICA', max_length=8, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo / Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='funiletapa',
            name='probabilidade_fechamento',
            field=models.IntegerField(default=0),
        ),
    ]
