# Generated by Django 5.2.4 on 2025-10-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0017_cliente_razao_social_cliente_tipo_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil_cliente',
            field=models.JSONField(blank=True, default=list, help_text='Lista de perfis/funções do cliente.', verbose_name='Perfis do Cliente (Interessado, Proprietário, etc.)'),
        ),
    ]
