# Generated by Django 5.2.4 on 2025-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0018_cliente_perfil_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='assinatura_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas_visitas/', verbose_name='Assinatura do Cliente'),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AddField(
            model_name='visita',
            name='localizacao_assinatura',
            field=models.CharField(blank=True, help_text='Lat/Long ou endereço GPS no momento da assinatura', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='realizada',
            field=models.BooleanField(default=False, verbose_name='Visita Realizada'),
        ),
    ]
