# Generated by Django 5.2.4 on 2025-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0019_visita_assinatura_cliente_visita_data_assinatura_and_more'),
        ('app_imoveis', '0012_remove_imovel_endereco_imovel_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='imovel',
        ),
        migrations.AddField(
            model_name='visita',
            name='imoveis',
            field=models.ManyToManyField(related_name='visitas', to='app_imoveis.imovel', verbose_name='Imóveis Visitados'),
        ),
    ]
