# Generated by Django 5.2.4 on 2025-11-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0020_remove_visita_imovel_visita_imoveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='assinatura_corretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas_visitas/', verbose_name='Assinatura do Corretor'),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_assinatura_corretor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura Corretor'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura Cliente'),
        ),
    ]
