# Generated by Django 5.2.4 on 2025-11-20 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0021_visita_assinatura_corretor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Corretor Responsável'),
        ),
    ]
