# Generated by Django 5.2.4 on 2025-08-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contratos', '0003_contrato_formas_pagamento'),
        ('app_imoveis', '0012_remove_imovel_endereco_imovel_complemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluguel', to='app_contratos.contrato')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='app_imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
            },
        ),
    ]
