# Generated by Django 5.2.4 on 2025-11-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alugueis', '0001_initial'),
        ('app_contratos', '0005_contrato_aluguel_alter_contrato_duracao_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_aluguel', to='app_contratos.contrato'),
        ),
    ]
