# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_alugueis', '0002_initial'),
        ('app_imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='app_imoveis.imovel'),
        ),
    ]
