# Generated by Django 5.2.4 on 2025-08-09 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0007_remove_oportunidade_data_proximo_contato'),
        ('app_contratos', '0004_alter_contrato_status_contrato'),
        ('core', '0008_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'unique_together': {('imobiliaria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Atual')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('numero_conta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Conta')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo de Transação')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Transação')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.categoria', verbose_name='Categoria')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.contabancaria', verbose_name='Conta Bancária')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contratos.contrato', verbose_name='Contrato (opcional)')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clientes.oportunidade', verbose_name='Oportunidade (opcional)')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'ordering': ['-data'],
            },
        ),
    ]
