# Generated by Django 5.2.4 on 2025-08-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='app_financeiro.categoria', verbose_name='Categoria Pai'),
        ),
    ]
