# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0002_initial'),
        ('app_contratos', '0003_initial'),
        ('app_financeiro', '0001_initial'),
        ('app_imoveis', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='conta',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clientes.cliente'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.conta'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='app_contratos.contrato'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.formapagamento'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='transacao_origem',
            field=models.ForeignKey(blank=True, help_text='Transação de Receita que originou este Repasse/Despesa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_repasse', to='app_financeiro.transacao', verbose_name='Transação de Origem'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('imobiliaria', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='conta',
            unique_together={('imobiliaria', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('imobiliaria', 'nome')},
        ),
    ]
