# Generated by Django 5.2.4 on 2025-08-09 13:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0002_categoria_pai'),
        ('core', '0008_notificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria Financeira', 'verbose_name_plural': 'Categorias Financeiras'},
        ),
        migrations.AlterModelOptions(
            name='contabancaria',
            options={'ordering': ['banco', 'nome'], 'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='oportunidade',
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='app_financeiro.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=7),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='agencia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='banco',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='numero_conta',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_bancaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_financeiro.contabancaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=7),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='contabancaria',
            unique_together={('imobiliaria', 'numero_conta')},
        ),
    ]
