# Generated by Django 5.0.1 on 2026-01-07 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Lançamento'),
        ),
    ]
