# Generated by Django 5.2.4 on 2025-08-22 21:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0008_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
        ('app_financeiro', '0002_popular_boleto_forma_pagamento'),
        ('core', '0010_imobiliaria_voz_da_marca_preferida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='conta_bancaria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('imobiliaria', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('imobiliaria', 'nome')},
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='transacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_clientes.cliente'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_vencimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.formapagamento'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'unique_together': {('imobiliaria', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.conta'),
        ),
        migrations.DeleteModel(
            name='ContaBancaria',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='pai',
        ),
    ]
