# Generated by Django 5.2.4 on 2025-08-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0003_alter_categoria_options_alter_contabancaria_options_and_more'),
        ('app_imoveis', '0009_alter_imagemimovel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_imoveis.imovel'),
        ),
    ]
