# Generated by Django 5.0.1 on 2026-01-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0006_historicaloportunidade_data_fechamento_prevista_and_more'),
        ('app_financeiro', '0003_alter_transacao_data_transacao'),
        ('app_imoveis', '0003_imovel_conteudo_html_autorizacao'),
        ('core', '0003_imobiliaria_foto_perfil'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_financeiras', to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_financeiras', to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento_financeiro', to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_financeiro.categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_cliente', to='app_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_financeiro.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.imobiliaria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_imovel', to='app_imoveis.imovel'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('imobiliaria', 'nome', 'tipo')},
        ),
    ]
