# Generated by Django 5.2.4 on 2025-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0003_remove_transacao_conta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text="Data efetiva do pagamento (apenas se status for 'PAGO').", null=True),
        ),
    ]
