# Generated by Django 5.2.4 on 2025-08-09 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0005_contrato_duracao_meses'),
        ('app_financeiro', '0004_transacao_imovel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Transação/Conta', 'verbose_name_plural': 'Transações e Contas'},
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='data',
        ),
        migrations.AddField(
            model_name='transacao',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='app_contratos.contrato'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10),
        ),
    ]
