# Generated by Django 5.2.4 on 2025-11-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0004_transacao_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='transacao_origem',
            field=models.ForeignKey(blank=True, help_text='Transação de Receita que originou este Repasse/Despesa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_repasse', to='app_financeiro.transacao', verbose_name='Transação de Origem'),
        ),
    ]
