# Generated by Django 5.2.4 on 2025-11-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_financeiro', '0005_transacao_transacao_origem'),
        ('app_financeiro', '000X_create_default_repasse_category'),
    ]

    operations = [
    ]
