# Generated by Django 5.2.4 on 2025-08-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_imoveis', '0009_alter_imagemimovel_options_and_more'),
        ('core', '0008_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('texto_gerado', models.TextField(help_text='O conteúdo do post gerado pela IA.')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('link_publicacao', models.URLField(blank=True, max_length=500, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='app_imoveis.imovel')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfilusuario')),
            ],
            options={
                'ordering': ['-data_publicacao'],
                'unique_together': {('imovel', 'plataforma', 'texto_gerado')},
            },
        ),
    ]
