# Generated by Django 5.0.1 on 2026-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('plataformas', models.JSONField(default=list, help_text="Lista de plataformas para publicar, ex: ['facebook', 'instagram']")),
                ('imagens_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs das imagens (ImagemImovel) selecionadas para este post.')),
                ('data_agendamento', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('PROCESSANDO', 'Processando'), ('PUBLICADO', 'Publicado com Sucesso'), ('ERRO', 'Erro na Publicação')], default='AGENDADO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_publicacao_real', models.DateTimeField(blank=True, help_text='Data e hora em que a publicação foi efetivamente realizada.', null=True)),
                ('resultado_publicacao', models.JSONField(blank=True, help_text='Armazena o resultado (sucesso ou erro) de cada plataforma.', null=True)),
            ],
            options={
                'verbose_name': 'Post Agendado',
                'verbose_name_plural': 'Posts Agendados',
                'ordering': ['data_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='PublicacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede_social', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('Outro', 'Outro')], max_length=50)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('link_publicacao', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Histórico de Publicação',
                'verbose_name_plural': 'Histórico de Publicações',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='PublicacaoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_gerado', models.TextField()),
                ('plataforma', models.CharField(max_length=50)),
                ('sucesso', models.BooleanField(default=False)),
                ('resposta_api', models.JSONField(blank=True, null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
