# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_imoveis', '0002_initial'),
        ('app_publicacoes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postagendado',
            name='agendado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postagendado',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_agendados_imobiliaria', to='core.imobiliaria'),
        ),
        migrations.AddField(
            model_name='postagendado',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_agendados', to='app_imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='publicacaohistorico',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_publicacoes', to='app_imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='publicacaosocial',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_sociais', to='app_imoveis.imovel'),
        ),
        migrations.AddField(
            model_name='publicacaosocial',
            name='publicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
