# Generated by Django 5.2.4 on 2025-08-13 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0009_alter_imagemimovel_options_and_more'),
        ('app_publicacoes', '0001_initial'),
        ('core', '0010_imobiliaria_voz_da_marca_preferida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacaosocial',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='publicacaosocial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publicacaosocial',
            name='resposta_api',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacaosocial',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_sociais', to='app_imoveis.imovel'),
        ),
        migrations.AlterField(
            model_name='publicacaosocial',
            name='plataforma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publicacaosocial',
            name='texto_gerado',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PostAgendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('plataformas', models.JSONField(default=list, help_text="Lista de plataformas para publicar, ex: ['facebook', 'instagram']")),
                ('data_agendamento', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('PUBLICADO', 'Publicado com Sucesso'), ('ERRO', 'Erro na Publicação')], default='AGENDADO', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_publicacao_real', models.DateTimeField(blank=True, help_text='Data e hora em que a publicação foi efetivamente realizada.', null=True)),
                ('resultado_publicacao', models.JSONField(blank=True, help_text='Armazena o resultado (sucesso ou erro) de cada plataforma.', null=True)),
                ('agendado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_criados', to='core.perfilusuario')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_agendados_imobiliaria', to='core.imobiliaria')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_agendados', to='app_imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Post Agendado',
                'verbose_name_plural': 'Posts Agendados',
                'ordering': ['data_agendamento'],
            },
        ),
        migrations.RemoveField(
            model_name='publicacaosocial',
            name='link_publicacao',
        ),
    ]
