# Generated by Django 5.2.4 on 2025-08-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis', '0012_remove_imovel_endereco_imovel_complemento_and_more'),
        ('app_publicacoes', '0002_alter_publicacaosocial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede_social', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('Outro', 'Outro')], max_length=50)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('link_publicacao', models.URLField(blank=True, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_publicacoes', to='app_imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Histórico de Publicação',
                'verbose_name_plural': 'Histórico de Publicações',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
