# Generated by Django 5.2.4 on 2025-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publicacoes', '0003_publicacaohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagendado',
            name='imagens_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs das imagens (ImagemImovel) selecionadas para este post.'),
        ),
        migrations.AlterField(
            model_name='postagendado',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('PROCESSANDO', 'Processando'), ('PUBLICADO', 'Publicado com Sucesso'), ('ERRO', 'Erro na Publicação')], default='AGENDADO', max_length=20),
        ),
    ]
