# Generated by Django 5.2.4 on 2025-08-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0008_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
        ('app_imoveis', '0010_imovel_posicao_chave'),
        ('core', '0010_imobiliaria_voz_da_marca_preferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel')], max_length=50, verbose_name='Tipo de Contrato')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total do Contrato')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('duracao_meses', models.PositiveIntegerField(default=12, help_text='Usado para gerar as parcelas de aluguel.', verbose_name='Duração do Contrato (em meses)')),
                ('status_contrato', models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Concluído', 'Concluído'), ('Rescindido', 'Rescindido'), ('Inativo', 'Inativo')], default='Pendente', max_length=50, verbose_name='Status do Contrato')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término (se aplicável)')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_imoveis.imovel', verbose_name='Imóvel')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_aluguel', to='app_clientes.cliente', verbose_name='Inquilino')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_propriedade', to='app_clientes.cliente', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Pagamento')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
