# Generated by Django 5.2.4 on 2025-08-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contratos', '0001_initial'),
        ('app_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='forma_pagamento_recebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.formapagamento', verbose_name='Forma de Pagamento Recebida'),
        ),
    ]
