# Generated by Django 5.2.4 on 2025-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status_contrato',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Concluído', 'Concluído'), ('Rescindido', 'Rescindido'), ('Inativo', 'Inativo')], default='Ativo', max_length=50, verbose_name='Status do Contrato'),
        ),
    ]
