# Generated by Django 5.0.1 on 2026-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contratos', '0001_initial'),
        ('app_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='formas_pagamento',
            field=models.ManyToManyField(blank=True, to='app_financeiro.formapagamento', verbose_name='Formas de Pagamento Aceitas'),
        ),
    ]
