# Generated by Django 5.0.1 on 2026-01-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clientes', '0002_initial'),
        ('app_contratos', '0002_initial'),
        ('app_financeiro', '0001_initial'),
        ('app_imoveis', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imobiliaria', verbose_name='Imobiliária'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_imoveis.imovel', verbose_name='Imóvel'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_aluguel', to='app_clientes.cliente', verbose_name='Inquilino'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_propriedade', to='app_clientes.cliente', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='modelocontrato',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_contrato', to='core.imobiliaria', verbose_name='Imobiliária'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modelo_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contratos.modelocontrato', verbose_name='Modelo de Contrato Utilizado'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_contratos.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma_pagamento_recebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financeiro.formapagamento', verbose_name='Forma de Pagamento Recebida'),
        ),
        migrations.AddConstraint(
            model_name='modelocontrato',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('imobiliaria', 'tipo_contrato'), name='unique_padrao_por_imobiliaria_tipo'),
        ),
    ]
