# Generated by Django 5.2.4 on 2025-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0002_initial'),
        ('app_financeiro', '0002_popular_boleto_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='formas_pagamento',
            field=models.ManyToManyField(blank=True, to='app_financeiro.formapagamento', verbose_name='Formas de Pagamento Aceitas'),
        ),
    ]
