# Generated by Django 5.2.4 on 2025-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0003_contrato_formas_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='conteudo_personalizado',
            field=models.TextField(blank=True, help_text='Armazena o conteúdo HTML do contrato após a edição.', null=True, verbose_name='Conteúdo Personalizado do Contrato'),
        ),
    ]
