# Generated by Django 5.2.4 on 2025-11-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0004_contrato_conteudo_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usado para gerar parcelas de aluguel.', max_digits=15, null=True, verbose_name='Valor do Aluguel (Mensal)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='duracao_meses',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Usado para gerar as parcelas de aluguel.', null=True, verbose_name='Duração do Contrato (em meses)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status_contrato',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('RESCINDIDO', 'Rescindido'), ('INATIVO', 'Inativo')], default='PENDENTE', max_length=50, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel')], max_length=50, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total do Contrato (Venda)'),
        ),
    ]
