# Generated by Django 5.2.4 on 2025-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0004_alter_contrato_status_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='duracao_meses',
            field=models.PositiveIntegerField(default=12, verbose_name='Duração do Contrato (em meses)'),
        ),
    ]
