# Generated by Django 5.2.4 on 2025-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0005_contrato_duracao_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='duracao_meses',
            field=models.PositiveIntegerField(default=12, help_text='Usado para gerar as parcelas de aluguel.', verbose_name='Duração do Contrato (em meses)'),
        ),
    ]
