# Generated by Django 5.2.4 on 2025-11-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0018_cliente_perfil_cliente'),
        ('app_contratos', '0005_contrato_aluguel_alter_contrato_duracao_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_como_fiador', to='app_clientes.cliente', verbose_name='Fiador'),
        ),
    ]
