# Generated by Django 5.2.4 on 2025-08-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0008_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
        ('app_contratos', '0006_alter_contrato_duracao_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.AddField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_aluguel', to='app_clientes.cliente', verbose_name='Inquilino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='proprietario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_propriedade', to='app_clientes.cliente', verbose_name='Proprietário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status_contrato',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Concluído', 'Concluído'), ('Rescindido', 'Rescindido'), ('Inativo', 'Inativo')], default='Pendente', max_length=50, verbose_name='Status do Contrato'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
