# Generated by Django 5.2.4 on 2025-11-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0018_cliente_perfil_cliente'),
        ('app_contratos', '0006_contrato_fiador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='fiador',
        ),
        migrations.AddField(
            model_name='contrato',
            name='fiadores',
            field=models.ManyToManyField(blank=True, related_name='contratos_como_fiador', to='app_clientes.cliente', verbose_name='Fiadores'),
        ),
    ]
