# Generated by Django 5.2.4 on 2025-08-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0007_remove_contrato_cliente_contrato_inquilino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='forma_pagamento_recebida',
            field=models.CharField(blank=True, choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência Bancária'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão de Crédito/Débito'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
