# Generated by Django 5.2.4 on 2025-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0007_remove_contrato_fiador_contrato_fiadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='taxa_administracao_percentual',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentual retido pela imobiliária sobre o aluguel.', max_digits=5, verbose_name='Taxa de Administração (%)'),
        ),
    ]
