# Generated by Django 5.2.4 on 2025-11-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0008_contrato_taxa_administracao_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='comissao_venda_percentual',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Percentual de comissão sobre o valor total da venda.', max_digits=5, verbose_name='Comissão de Venda (%)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_comissao_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor final acordado. Usado para lançar a RECEITA.', max_digits=15, null=True, verbose_name='Valor Final da Comissão (R$)'),
        ),
    ]
