# Generated by Django 5.2.4 on 2025-08-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0009_contrato_formas_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='condicoes_pagamento',
        ),
    ]
