# Generated by Django 5.2.4 on 2025-11-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0009_contrato_comissao_venda_percentual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='duracao_meses',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Usado para gerar parcelas de aluguel.', null=True, verbose_name='Duração do Contrato (em meses)'),
        ),
    ]
