# Generated by Django 5.2.4 on 2025-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0010_remove_contrato_condicoes_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
    ]
