# Generated by Django 5.2.4 on 2025-11-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0010_alter_contrato_duracao_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_primeiro_vencimento',
            field=models.DateField(blank=True, help_text='Data do primeiro vencimento para gerar as parcelas de aluguel.', null=True, verbose_name='Data do 1º Vencimento (Aluguel)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_vencimento_venda',
            field=models.DateField(blank=True, help_text='Data limite para o pagamento da comissão ou quitação da venda.', null=True, verbose_name='Data Venc. Comissão/Quitação (Venda)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='duracao_meses',
            field=models.PositiveIntegerField(blank=True, default=12, help_text='Usado para gerar as parcelas de aluguel.', null=True, verbose_name='Duração do Contrato (em meses)'),
        ),
    ]
