# Generated by Django 5.2.4 on 2025-11-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0011_contrato_data_primeiro_vencimento_and_more'),
        ('core', '0012_imobiliaria_cnpj_imobiliaria_creci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Contrato de Aluguel Residencial (Padrão)', max_length=255, verbose_name='Nome do Modelo')),
                ('tipo_contrato', models.CharField(choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel')], max_length=50, verbose_name='Tipo de Contrato')),
                ('conteudo', models.TextField(help_text='Cole aqui o HTML do contrato. Use variáveis como {{ inquilino.nome }}.', verbose_name='Conteúdo do Modelo (HTML/Django)')),
                ('padrao', models.BooleanField(default=False, help_text='Marque se este for o modelo padrão para este tipo de contrato.', verbose_name='Modelo Padrão')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_contrato', to='core.imobiliaria', verbose_name='Imobiliária')),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contrato',
                'ordering': ['imobiliaria', 'tipo_contrato', '-padrao', 'nome'],
                'unique_together': {('imobiliaria', 'tipo_contrato', 'padrao')},
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='modelo_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contratos.modelocontrato', verbose_name='Modelo de Contrato Utilizado'),
        ),
    ]
