# Generated by Django 5.2.4 on 2025-11-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0012_modelocontrato_contrato_modelo_utilizado'),
        ('core', '0012_imobiliaria_cnpj_imobiliaria_creci'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelocontrato',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='modelocontrato',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('imobiliaria', 'tipo_contrato'), name='unique_padrao_por_imobiliaria_tipo'),
        ),
    ]
