# Generated by Django 5.2.4 on 2025-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contratos', '0013_alter_modelocontrato_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status_contrato',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('RESCINDIDO', 'Rescindido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=50, verbose_name='Status do Contrato'),
        ),
    ]
